name: 📚 Documentation Improvement
description: Suggest improvements to documentation
title: "[Docs]: "
labels: ["documentation", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation! Clear and comprehensive docs are essential for a great user experience.

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting your documentation request
      options:
        - label: I have searched existing issues to ensure this documentation improvement hasn't been requested before
          required: true
        - label: I have reviewed the current [documentation](https://browser-agent.readthedocs.io)
          required: true
        - label: I have checked if this information exists elsewhere in the docs
          required: false

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation improvement are you suggesting?
      options:
        - Missing Documentation
        - Incorrect/Outdated Information
        - Unclear Instructions
        - Missing Examples
        - API Documentation
        - Tutorial/Guide
        - FAQ Addition
        - Installation Instructions
        - Configuration Guide
        - Troubleshooting
        - Best Practices
        - Migration Guide
        - Other (please specify in description)
    validations:
      required: true

  - type: dropdown
    id: doc-section
    attributes:
      label: Documentation Section
      description: Which section of the documentation does this relate to?
      options:
        - Getting Started
        - Installation
        - Configuration
        - User Guide
        - API Reference
        - Tutorials
        - Examples
        - FAQ
        - Troubleshooting
        - Contributing
        - Development Setup
        - Plugin Development
        - Browser Integration
        - AI Integration
        - CLI Reference
        - GUI Guide
        - Web Interface
        - Performance
        - Security
        - Deployment
        - Multiple Sections
        - New Section Needed
        - Other (please specify in description)
    validations:
      required: true

  - type: dropdown
    id: audience
    attributes:
      label: Target Audience
      description: Who is the primary audience for this documentation?
      options:
        - New Users
        - Experienced Users
        - Developers
        - Plugin Developers
        - System Administrators
        - Contributors
        - All Users
        - Other (please specify in description)
    validations:
      required: true

  - type: textarea
    id: current-issue
    attributes:
      label: Current Documentation Issue
      description: Describe what's wrong, missing, or unclear in the current documentation
      placeholder: |
        Describe the specific issue with the current documentation:
        
        - What information is missing?
        - What is incorrect or outdated?
        - What is confusing or unclear?
        - Where did you get stuck?
    validations:
      required: true

  - type: input
    id: doc-url
    attributes:
      label: Documentation URL
      description: If applicable, provide the URL of the documentation page that needs improvement
      placeholder: "https://browser-agent.readthedocs.io/en/latest/..."

  - type: textarea
    id: expected-content
    attributes:
      label: Expected Content
      description: Describe what you expected to find in the documentation
      placeholder: |
        What information were you looking for?
        What did you expect the documentation to explain?
    validations:
      required: true

  - type: textarea
    id: proposed-improvement
    attributes:
      label: Proposed Improvement
      description: Describe how you think the documentation should be improved
      placeholder: |
        Suggest specific improvements:
        
        - What content should be added?
        - How should existing content be modified?
        - What examples would be helpful?
        - How should the information be organized?
    validations:
      required: true

  - type: textarea
    id: user-journey
    attributes:
      label: User Journey
      description: Describe the user journey that led you to this documentation issue
      placeholder: |
        Describe your experience:
        
        1. What were you trying to accomplish?
        2. Where did you start looking for information?
        3. What steps did you take?
        4. Where did you get stuck or confused?
        5. How did you eventually solve the problem (if you did)?

  - type: textarea
    id: examples-needed
    attributes:
      label: Examples Needed
      description: What specific examples would help illustrate the concept or feature?
      placeholder: |
        Describe examples that would be helpful:
        
        - Code examples
        - Configuration examples
        - Use case scenarios
        - Step-by-step walkthroughs
        - Screenshots or diagrams
      render: markdown

  - type: textarea
    id: code-example
    attributes:
      label: Suggested Code Example
      description: If applicable, provide a code example that should be included
      placeholder: |
        # Example code that would be helpful
        from brouser_agent import BrowserAgent
        
        # Your example here...
      render: python

  - type: textarea
    id: config-example
    attributes:
      label: Suggested Configuration Example
      description: If applicable, provide a configuration example that should be included
      placeholder: |
        # Example configuration
        browser:
          type: chrome
          headless: false
        
        # Your configuration example here...
      render: yaml

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this documentation improvement?
      options:
        - Critical (blocking users from using the feature)
        - High (significantly impacts user experience)
        - Medium (would improve user experience)
        - Low (minor improvement)
    validations:
      required: true

  - type: dropdown
    id: difficulty
    attributes:
      label: Difficulty Level
      description: What difficulty level should this documentation target?
      options:
        - Beginner (new to browser automation)
        - Intermediate (some experience with automation)
        - Advanced (experienced with automation tools)
        - Expert (deep technical knowledge)
        - All Levels (should be accessible to everyone)
    validations:
      required: true

  - type: textarea
    id: related-docs
    attributes:
      label: Related Documentation
      description: Are there other documentation pages that should be updated or linked?
      placeholder: |
        List related documentation that might need updates:
        
        - Pages that should link to this content
        - Pages that contain related information
        - Pages that might conflict with new content

  - type: textarea
    id: external-resources
    attributes:
      label: External Resources
      description: Are there external resources that provide good examples of how this should be documented?
      placeholder: |
        Links to external resources:
        
        - Other projects with good documentation on this topic
        - Blog posts or tutorials
        - Stack Overflow answers
        - Official specifications or standards

  - type: dropdown
    id: format-preference
    attributes:
      label: Format Preference
      description: What format would work best for this documentation?
      options:
        - Text with Code Examples
        - Step-by-Step Tutorial
        - Video Tutorial
        - Interactive Examples
        - Diagrams/Flowcharts
        - Screenshots
        - FAQ Format
        - Reference Table
        - Comparison Chart
        - Multiple Formats
        - Other (please specify in additional context)
    validations:
      required: false

  - type: textarea
    id: search-terms
    attributes:
      label: Search Terms
      description: What terms did you search for when looking for this information?
      placeholder: |
        List the search terms you used:
        
        - Terms you searched in the documentation
        - Google search terms
        - Terms that should find this content

  - type: textarea
    id: common-mistakes
    attributes:
      label: Common Mistakes
      description: What common mistakes or misconceptions should the documentation address?
      placeholder: |
        Common issues that users might encounter:
        
        - Typical configuration errors
        - Common misunderstandings
        - Frequent support questions
        - Edge cases to be aware of

  - type: textarea
    id: success-criteria
    attributes:
      label: Success Criteria
      description: How would you know if this documentation improvement is successful?
      placeholder: |
        Define success criteria:
        
        - Users can complete task X without additional help
        - Reduced support questions about topic Y
        - Improved user onboarding experience
        - Faster time to first success

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about this documentation improvement
      placeholder: |
        Any additional information:
        
        - Screenshots of current documentation
        - Links to related discussions
        - Community feedback
        - Support ticket references

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you like to contribute to improving this documentation?
      options:
        - label: I would like to write the improved documentation
          required: false
        - label: I can provide additional examples
          required: false
        - label: I can review and test the documentation
          required: false
        - label: I can provide screenshots or diagrams
          required: false
        - label: I can help with translation
          required: false

  - type: checkboxes
    id: impact
    attributes:
      label: Expected Impact
      description: What impact do you expect this documentation improvement to have?
      options:
        - label: Reduce user confusion
          required: false
        - label: Improve onboarding experience
          required: false
        - label: Reduce support requests
          required: false
        - label: Increase feature adoption
          required: false
        - label: Improve developer experience
          required: false
        - label: Attract new users
          required: false